---
title: "Confidence intervals in the CMET for a classifier"
author: "Francisco J. Valverde Albacete"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Confidence Intervals for a classifier in the CMET}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette explores how does uncertainty of classification results manifest itself in the CMET.

# Environment construction

```{r environment, echo=FALSE, results="hide"}
#library(ggtern)   # Excellent package for ternary diagrams in the gg tradition
#library(entropy)  # To work out the appropriate coordinates.
library(dplyr)     # That infamous Mr. Wickham!
library(tidyr)     # Tidying tall & wide dataframes
library(infotheo)  # The functionality provided by this has to be rerouted through entropies
library(entropies) # This package
library(ggtern)    # Ternary diagrams on ggplot
library(caret)     # Adopt caret's Weltanschauung for ML
#library(vcd)       # Categorical benchmarks
library(mlbench)   # ml benchmarkss
#knitr::opts_chunk$set(dev = 'pdf') # plots in pdf, better for publication
#knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_chunk$set(comment=NA, fig.width=6, fig.height=6)
```

# Data preparation

The following code is extracted from caret's main vignette:

```{r classify}
# from: http://machinelearningmastery.com/how-to-estimate-model-accuracy-in-r-using-the-caret-package/
# load the library
#library(caret)
# load the iris dataset
data(iris)
# define training control
train_control <- trainControl(method="cv", 
                              number=10,
                              returnData = TRUE,                   
                              savePredictions="all"
                            )
# fix the parameters of the algorithm: Naive Bayes
thisGrid <- expand.grid(fL=c(0), usekernel=c(FALSE), adjust=c(0)) # These parameters depend on Naive Bayes!
# train the model
thisModel <- train(Species~., 
                   data=iris, 
                   trControl=train_control, 
                   method="nb", 
                   tuneGrid=thisGrid, # These parameters depend on Naive Bayes!
                   savePredictions="all"
                   )
# summarize results
print(thisModel)
```

## Evaluation on the the test set for each fold

```{r}
predictions <- thisModel$pred#This has the preds and obs for each fold and value of the grid
ct  <- table(predictions %>% dplyr::select(pred, obs, Resample))# 'Resample' is the grid.
#obtain the informations
ents <-  jentropies(ct)
```


 
# From the caret book

```{r}
# data importing
library(mlbench)
data(Sonar)
str(Sonar[, 1:10])
# data splitting
library(caret)
set.seed(998)
inTraining <- createDataPartition(Sonar$Class, p = .75, list = FALSE)
training <- Sonar[ inTraining,]
testing  <- Sonar[-inTraining,]
```

## With cross validation

```{r}
set.seed(119)
k <- 10 # num. of folds
dataClass <- Sonar$Class # Different for each database!
folds <- createFolds(dataClass, k,)
#generate a list of confusion matrices by going over the rest of the folds
```

# Postscriptum

```{r ps}
sessionInfo()
```

<!-- # TO BE DELETED, FROM HERE ONWARDS -->
<!-- Vignettes are long form documentation commonly included in packages. Because they are part of the distribution of the package, they need to be as compact as possible. The `html_vignette` output type provides a custom style sheet (and tweaks some options) to ensure that the resulting html is as small as possible. The `html_vignette` format: -->

<!-- - Never uses retina figures -->
<!-- - Has a smaller default figure size -->
<!-- - Uses a custom CSS stylesheet instead of the default Twitter Bootstrap style -->

<!-- ## Vignette Info -->

<!-- Note the various macros within the `vignette` section of the metadata block above. These are required in order to instruct R how to build the vignette. Note that you should change the `title` field and the `\VignetteIndexEntry` to match the title of your vignette. -->

<!-- ## Styles -->

<!-- The `html_vignette` template includes a basic CSS theme. To override this theme you can specify your own CSS in the document metadata as follows: -->

<!--     output:  -->
<!--       rmarkdown::html_vignette: -->
<!--         css: mystyles.css -->

<!-- ## Figures -->

<!-- The figure sizes have been customised so that you can easily put two images side-by-side.  -->

<!-- ```{r, fig.show='hold'} -->
<!-- plot(1:10) -->
<!-- plot(10:1) -->
<!-- ``` -->

<!-- You can enable figure captions by `fig_caption: yes` in YAML: -->

<!--     output: -->
<!--       rmarkdown::html_vignette: -->
<!--         fig_caption: yes -->

<!-- Then you can use the chunk option `fig.cap = "Your figure caption."` in **knitr**. -->

<!-- ## More Examples -->

<!-- You can write math expressions, e.g. $Y = X\beta + \epsilon$, footnotes^[A footnote here.], and tables, e.g. using `knitr::kable()`. -->

<!-- ```{r, echo=FALSE, results='asis'} -->
<!-- knitr::kable(head(mtcars, 10)) -->
<!-- ``` -->

<!-- Also a quote using `>`: -->

<!-- > "He who gives up [code] safety for [code] speed deserves neither." -->
<!-- ([via](https://twitter.com/hadleywickham/status/504368538874703872)) -->
