---
title: "Classification analysis using CMET"
author: "Francisco J. Valverde-Albacete & Carmen Peláez Moreno"
date: "Feb, 15th, 2016"
output: html_document
---

# Environment construction

```{r, echo=FALSE, environment}
library(tidyverse)  # That (in)famous Mr. Wickham!
#library(dplyr)     # That (in)famous Mr. Wickham!
#library(tidyr)     # Tidying tall & wide dataframes
#library(infotheo)  # The functionality provided by this has to be rerouted through entropies
library(entropies) # This package
library(ggtern)    # Ternary diagrams on ggplot
library(vcd)       # Categorical benchmarks
library(mlbench)   # ml benchmarkss
library(candisc)   # Wine dataset
#knitr::opts_chunk$set(dev = 'pdf') # plots in pdf, better for publication
knitr::opts_chunk$set(comment=NA, fig.width=6, fig.height=4)
fancy <- TRUE  # set this for nicer on-screen visualization
fancy <- FALSE # Set this for either printing matter or...
```

# Classification data analysis using the SCET

## Datasets available for entropy analysis in this package

```{r data-munging}
# the inventory of databases you can access
#library(datasets)
dsNames <- c("Ionosphere", "iris", "Glass", "Arthritis", "BreastCancer", "Sonar", "Wine") # 
className <- c("Class","Species", "Type", "Improved", "Class", "Class", "Cultivar")  # Name of class attribute
classVar <- c(35, 5, 10, 5, 11, 61, 1)   # ordinal of the class attribute
idNumber <- c(NaN, NaN, NaN, 1, 1, NaN, NaN) # Other attributes to dispose of: mainly identifiers.

K <- c(2, 3, 7, 3, 2, 2, 3)  # No. of classes in the class variable
# To select a dataset by name
# Caveat: you have to ensure that the containing package has been attached
evalDataset <- function(dsName){
    dsName <- as.character(dsName)
    switch(dsName, #TODO: improve this way of "invoking" the dataset.
        "iris" =         {data(iris); iris},
        "Ionosphere" =   {data(Ionosphere); Ionosphere},
        "Glass" =        {data(Glass); Glass},
        "Arthritis" =    {data(Arthritis); Arthritis},
        "BreastCancer" = {data(BreastCancer); BreastCancer},
        "Sonar" =        {data(Sonar); Sonar},
        "Wine" =         {data(Wine); Wine}
    ) #This value "FALLS THROUGH"
}
m <- sapply(dsNames, function(n){nrow(evalDataset(n))}) # no. of instances in the dataset
n <- sapply(dsNames, function(n){ncol(evalDataset(n))}) - 1 - as.numeric(!is.nan(idNumber)) # no. of features in the dataset.
datasets <- data.frame(name=dsNames, 
                       className, 
                       idNumber, 
                       K=as.integer(K), 
                       n=as.integer(n), 
                       m, 
                       stringsAsFactors=FALSE)
# #To select the #of column of the classc
# whichClass <- function(ds, className){which(colnames(evalDatasset(ds))==className)}
# #whichNumVar <-  function(r){whichClass(evalDataset(r$name), r$className)}
# cardinalClass <- function(ds, className){
#     length(unique(evalDataset(ds)[,className]))
# }
# classVar <-  mapply(whichClass, datasets$name, datasets$className)
# K <- mapply(cardinalClass, datasets$name, classVar)
# library(dplyr)
# datasets <- data.frame(name,className, classVar, K)
datasets
```

Let's print this information to latex:

```{r}
library(xtable)
ds4latexing <- datasets %>% dplyr::select(-className, -idNumber)
row.names(ds4latexing) <- NULL
names(ds4latexing) <- c("Dataset Name", "class card.", "num. features", "num. instances")
thisLatex <- xtable(ds4latexing, 
                    caption="Some datasets considered in this study",
                    label="tab:datasets")
align(thisLatex) <- xalign(thisLatex)
thisLatex
```

## Obtaining the entropies

Obtain the entropies and some other data for plotting from all datasets.

```{r find-entropies}
edf <- data.frame()
for(dsName in unique(datasets$name)){
    dsRecord <-  filter(datasets, name == dsName)
    ds <- evalDataset(dsName)
#    for(withClass in withClasses){
#        if (withClass){
            print(sprintf("Analyzing dataset with class label: %s", dsName))
#        }else {
#            print(sprintf("Analyzing dataset without class label: %s", dsName))
            # as per: 
            # http://stackoverflow.com/questions/5234117/how-to-drop-columns-by-name-in-a-data-frame
            # Don't EVER use subset in PROGRAMS!
            #ds <- subset(ds, subset=1:nrow(ds), select=dsRecord$className, drop=TRUE)
#            ds <- ds[, !colnames(ds) == dsRecord$className] #fastest in bechnmark at bot. of url
#        }
        #Kdataset <- select(ds, which(names(ds) == dsRecord$className))
        Kdataset <- dplyr::select(ds, matches(dsRecord$className))
        Xdataset <- dplyr::select(ds, -matches(dsRecord$className))
        edf <- rbind(edf,
                     cbind(dsName,
                           transform="observation",
                           jentropies(Kdataset,Xdataset)# entropies of observations
                           )
#                     sentropies(ds, nbins=ceiling(nrow(ds)^(1/3))) %>%
                    )
        #select those columns which are numeric
        numColumns <- sapply(Xdataset, is.numeric)
        if (!any(numColumns)) next
        #catColumns <- !numColumns#categorical columns in X (not including the class)
        Tdataset <- Xdataset[,numColumns]#Until  we know how to apply Box-Cox
        # Tdataset <- log(Xdataset)#Box-Cox transformation
        # edf <- rbind(edf,
        #              cbind(dsName,
        #                    transform="Box-Cox:log",
        #                    jentropies(Xdataset,Tdataset)
        #                    )
        #              )
        pca <- prcomp(Tdataset, center = TRUE, scale. = TRUE) 
        Ydataset <- cbind(
                        Xdataset[,!numColumns],
                        predict(pca, newdata=Tdataset)
        )
        edf <- rbind(edf,
                     cbind(dsName, 
                           transform="PCAonBoxCox:log",
                           jentropies(Tdataset, Ydataset)
                           )
        )
}
str(edf)
# show the split entropies
#filter(edf, type != "XY")
#show all entropies for a data base
print(filter(edf, dsName == "iris"))
```

Visualize both the aggregate and the split entropies.

```{r, fig.width=12, fig.height=16}
fancy <- TRUE
fancy <- FALSE
#select some entropies to visualize
cmet <- ggmetern(edf %>% filter(type != "XY"), 
                 #filter(edf, type != "XY"),#alternative not to visualize the aggregate
                 fancy) +
    geom_point(aes(color=transform, shape=type), size=3) +
    scale_shape_manual(values=c(4, 20, 1)) +
    labs(color="Dataset name", shape="Var type")
cmet + facet_wrap(~dsName, ncol=2)
#dev.off()#Necessary to do the textual plot.
#ggsave(str_interp("entropyEndToEnd_${dsName}_epoch_${thisEpoch}.jpeg"), plot=e2ePlot)
```

# Postscriptum

```{r ps}
sessionInfo()
```


